### ISSUE TITLE
New release with warning fixes

### ISSUE THREAD

**Issue by axelson** [timberio/timber-elixir-ecto#8]
Is it possible for a new release of timber_ecto to be cut that includes: https://github.com/timberio/timber-elixir-ecto/pull/4 ? We try to keep warnings out of our code as much as possible, including warnings from dependencies. Although this one is particularly annoying since it appears on the run of every test that touches a `Repo`.

**Comment by mitchellhenke** [comment]
@axelson sorry for the delay (and excessive warnings).  `2.1.0` has been released to hex with the warnings fixed 🙂

**Comment by axelson** [comment]
Awesome, thanks!
